print ("DDDDD     RRRRRRRRR   ")
print ("D    D    RR      RR")
print ("D     D   RR      RR ")
print ("D     D   RR      RR ")
print ("D     D   RRRRRRRR")
print ("D     D   RR     RR")
print ("D     D   RR      RR ")
print ("D    D    RR       RR")
print ("DDDDD     RR        RR")